CREATE SEQUENCE SQ_USER
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 1;

CREATE TABLE T_SIP_USER(
    userId INTEGER DEFAULT nextval('SQ_USER') PRIMARY KEY,
    name VARCHAR(100) NOT NULL ,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(100) NOT NULL
);