CREATE SEQUENCE  SQ_DRINK
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 1;

CREATE TABLE T_SIP_DRINK(
    ID INTEGER DEFAULT  NEXTVAL('SQ_DRINK') PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    PRICE DECIMAL NOT NULL
);